variables:
  # Set to true to skip tests
  SKIP_TESTS: "false"

stages:
  - test
  - trigger

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:
  except:
    variables:
      - $SKIP_TESTS == "true"
  stage: test
  image: ubuntu:focal
  services:
    - docker:dind
  tags:
    - mender-qa-slave
  variables:
    # DinD setup in mender-qa-slave
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apt-get update && apt-get install -y
      docker.io bash git openssl pwgen python3 jq docker-compose wget sudo
    - git config --global user.name "user"
    - git config --global user.email "user@example.com"
  script:
    - ./run-tests.sh

test:internal-links:
  stage: test
  image: node:14-alpine
  script:
    - apk add --no-cache git
    - npm install
    - ./checklinks --color --verbose

test:passive-voice:
    stage: test
    image: ubuntu
    script:
        - bash ./scripts/run-passive.sh

test:latest_versions:
  stage: test
  image: alpine
  before_script:
    - apk add --no-cache git python3 py3-pip
    - pip3 install pyyaml
    - export INTEGRATION_REPO_DIR=/tmp/integration
    - git clone https://github.com/mendersoftware/integration.git $INTEGRATION_REPO_DIR
    - export INTEGRATION_VERSION=origin/staging
  script:
    - ./autoversion.py
      --update
      --integration-dir $INTEGRATION_REPO_DIR
      --integration-version $INTEGRATION_VERSION
    - git diff HEAD
    # exits with non zero status if not staged for commit files exist
    - git diff-index --quiet HEAD
  only:
    - /^(hosted)$/

trigger:mender-docs-site:
  image: alpine
  stage: trigger
  before_script:
    - apk add --no-cache curl
  script:
    - curl -v -f -X POST
      -F token=$MENDER_DOCS_SITE_TRIGGER_TOKEN
      -F ref=master
      https://gitlab.com/api/v4/projects/16842368/trigger/pipeline
    - curl -v -f -X POST
      -F token=$MENDER_DOCS_SITE_TRIGGER_TOKEN
      -F ref=production
      https://gitlab.com/api/v4/projects/16842368/trigger/pipeline
  only:
    - /^(master|hosted|[0-9]+\.[0-9]+\.x)$/
