variables:
  # Set to true to skip tests
  SKIP_TESTS: "false"

stages:
  - test
  - trigger

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:
  except:
    variables:
      - $SKIP_TESTS == "true"
  stage: test
  image: ubuntu:focal
  services:
    - docker:dind
  tags:
    - mender-qa-worker-generic
  variables:
    # DinD setup in Mender CI runners
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apt-get update && apt-get install -y
      docker.io bash git openssl pwgen python3 jq docker-compose wget sudo
    - git config --global user.name "user"
    - git config --global user.email "user@example.com"
  script:
    - ./run-tests.sh

test:internal-links:
  stage: test
  image: node:14-alpine
  script:
    - apk add --no-cache git
    - npm install
    - ./checklinks --color --verbose

test:passive-voice:
    stage: test
    image: ubuntu
    script:
        - bash ./scripts/run-passive.sh

test:latest_versions:
  stage: test
  image: alpine
  before_script:
    - apk add --no-cache git python3 py3-pip openssh-client
    - pip3 install pyyaml
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Host github.com" > ~/.ssh/config
    - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    - export MENDER_BINARY_DELTA_DIR=/tmp/mender-binary-delta
    - export INTEGRATION_REPO_DIR=/tmp/integration
    - export MENDER_CONVERT_DIR=/tmp/mender-convert
    - export MENDER_CLIENT_DIR=/tmp/mender-client
    - git clone git@github.com:mendersoftware/mender-binary-delta.git $MENDER_BINARY_DELTA_DIR
    - git clone https://github.com/mendersoftware/integration.git $INTEGRATION_REPO_DIR
    - git clone https://github.com/mendersoftware/mender-convert $MENDER_CONVERT_DIR
    - git clone https://github.com/mendersoftware/mender $MENDER_CLIENT_DIR
    - export INTEGRATION_VERSION=origin/staging
  script:
    - export MENDER_CLIENT_VERSION=$(cd $MENDER_CLIENT_DIR ; git tag | egrep -e '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V -r | head -n1)
    - export MENDER_CONVERT_VERSION=$(cd $MENDER_CONVERT_DIR ; git tag | egrep -e '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V -r | head -n1)
    - export MENDER_BINARY_DELTA_VERSION=$(cd $MENDER_BINARY_DELTA_DIR ; git tag | egrep -e '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V -r | head -n1)
    - ./autoversion.py
      --update
      --mender-convert-version $MENDER_CONVERT_VERSION
      --mender-binary-delta-version $MENDER_BINARY_DELTA_VERSION
      --integration-dir $INTEGRATION_REPO_DIR
      --integration-version $INTEGRATION_VERSION
    - git diff HEAD
    # exits with non zero status if not staged for commit files exist
    - git diff-index --quiet HEAD
  only:
    - /^(hosted)$/

.trigger:mender-docs-site:
  stage: trigger
  inherit:
    variables: false
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|hosted|[0-9]+\.[0-9]+\.x)$/'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never

trigger:mender-docs-site:master:
  extends: .trigger:mender-docs-site
  trigger:
    project: Northern.tech/Mender/mender-docs-site
    branch: master

trigger:mender-docs-site:production:
  extends: .trigger:mender-docs-site
  trigger:
    project: Northern.tech/Mender/mender-docs-site
    branch: production
